# Generated by Django 3.0.7 on 2020-06-05 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_RecordTime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=100, verbose_name='具体活动')),
            ],
        ),
        migrations.CreateModel(
            name='EventType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=10, verbose_name='活动类型')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(max_length=10, verbose_name='所属项目')),
            ],
        ),
        migrations.CreateModel(
            name='RecordTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_year', models.IntegerField(verbose_name='年')),
                ('event_month', models.IntegerField(verbose_name='月')),
                ('event_day', models.IntegerField(verbose_name='日')),
                ('event_week', models.IntegerField(verbose_name='周')),
                ('event_description', models.CharField(max_length=255, verbose_name='活动描述')),
                ('begin_time', models.DateTimeField(verbose_name='开始时间')),
                ('end_time', models.DateTimeField(verbose_name='结束时间')),
                ('time_duration', models.IntegerField(verbose_name='耗用时长(min)')),
                ('record_time', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_RecordTime.Event', verbose_name='具体活动')),
                ('event_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_RecordTime.EventType', verbose_name='活动类型')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_RecordTime.Project', verbose_name='所属项目')),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='event_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_RecordTime.EventType'),
        ),
    ]
