# Generated by Django 3.0.7 on 2020-06-05 00:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_RecordMoney', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=10, verbose_name='账户')),
            ],
        ),
        migrations.CreateModel(
            name='DetailAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail_account', models.CharField(max_length=10, verbose_name='明细科目')),
            ],
        ),
        migrations.CreateModel(
            name='FirstLevelAccounts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_level_account', models.CharField(max_length=10, verbose_name='一级科目')),
            ],
        ),
        migrations.CreateModel(
            name='IncomeAndExpenditureType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('income_and_expenditure_type', models.CharField(max_length=10, verbose_name='收支类型')),
            ],
        ),
        migrations.CreateModel(
            name='RecordMoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trading_year', models.IntegerField(verbose_name='年')),
                ('trading_month', models.IntegerField(verbose_name='月')),
                ('trading_week', models.IntegerField(verbose_name='周')),
                ('trading_day', models.IntegerField(verbose_name='日')),
                ('trading_period', models.IntegerField(verbose_name='所属期间')),
                ('trader', models.CharField(max_length=20, verbose_name='交易商家')),
                ('summary', models.CharField(max_length=255, verbose_name='摘要')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='金额(元)')),
                ('record_time', models.DateTimeField(auto_now_add=True, verbose_name='记录时间')),
                ('trading_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_RecordMoney.Account', verbose_name='账户')),
                ('trading_detail_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_RecordMoney.DetailAccounts', verbose_name='明细科目')),
                ('trading_first_level_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_RecordMoney.FirstLevelAccounts', verbose_name='一级科目')),
                ('trading_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_RecordMoney.IncomeAndExpenditureType', verbose_name='收支类型')),
            ],
        ),
        migrations.AddField(
            model_name='firstlevelaccounts',
            name='income_and_expenditure_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_RecordMoney.IncomeAndExpenditureType'),
        ),
        migrations.AddField(
            model_name='detailaccounts',
            name='first_level_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_RecordMoney.FirstLevelAccounts'),
        ),
        migrations.AddField(
            model_name='detailaccounts',
            name='income_and_expenditure_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_RecordMoney.IncomeAndExpenditureType'),
        ),
    ]
